### ISSUE TITLE
Issue installing code OSX and Debian

### ISSUE THREAD

**Issue by lazersos** [svalinn/parastell#179]
I'm having trouble getting `parastell` installed on either MacOS (12.7.6, x86) or on my Debian machine (GNU/Linux 12, 6.1.0-28-amd64, x86).  On the mac I tried following your intall instructions using `miniconda` but when I try to run the example `config.yml` I get the following error:

```
../executables/parastell config.yaml
Traceback (most recent call last):
  File "/Users/lazerson/Sims_Work/PARASTELL/Examples/../executables/parastell", line 3, in <module>
    from parastell import parastell
  File "/Users/lazerson/Sims_Work/PARASTELL/parastell/parastell.py", line 5, in <module>
    import cubit
  File "/Applications/Coreform-Cubit-2023.11.app/Contents/lib/cubit.py", line 44, in <module>
    from cubit3 import *
  File "/Applications/Coreform-Cubit-2023.11.app/Contents/lib/cubit3.py", line 12, in <module>
    import _cubit3
ImportError: dlopen(/Applications/Coreform-Cubit-2023.11.app/Contents/lib/_cubit3.so, 0x0002): Symbol not found: (_iconv)
  Referenced from: '/Applications/Coreform-Cubit-2023.11.app/Contents/lib/libCATSysTS.dylib'
  Expected in: '/Users/lazerson/miniconda3/envs/parastell_env/lib/libiconv.2.dylib'
```

For reference Coreform-Cubit runs fine on it's own.  This may be an OSX issue so no big deal, I have the Debian machine. However on that machine I get a different error:

```
WARNING:root:Mayavi not found. 3D plots will not work.
Traceback (most recent call last):
  File "/home/lazerson/src/parastell/Examples/../executables/parastell", line 3, in <module>
    from parastell import parastell
  File "/home/lazerson/src/parastell/parastell/parastell.py", line 10, in <module>
    from . import invessel_build as ivb
  File "/home/lazerson/src/parastell/parastell/invessel_build.py", line 8, in <module>
    import cadquery as cq
  File "/home/lazerson/anaconda3/envs/parastell_env/lib/python3.11/site-packages/cadquery/__init__.py", line 22, in <module>
    from .occ_impl import exporters
  File "/home/lazerson/anaconda3/envs/parastell_env/lib/python3.11/site-packages/cadquery/occ_impl/exporters/__init__.py", line 10, in <module>
    from ...cq import Workplane
  File "/home/lazerson/anaconda3/envs/parastell_env/lib/python3.11/site-packages/cadquery/cq.py", line 62, in <module>
    from .sketch import Sketch
  File "/home/lazerson/anaconda3/envs/parastell_env/lib/python3.11/site-packages/cadquery/sketch.py", line 28, in <module>
    from .occ_impl.sketch_solver import (
  File "/home/lazerson/anaconda3/envs/parastell_env/lib/python3.11/site-packages/cadquery/occ_impl/sketch_solver.py", line 3, in <module>
    from nptyping import NDArray as Array
  File "/home/lazerson/anaconda3/envs/parastell_env/lib/python3.11/site-packages/nptyping/__init__.py", line 32, in <module>
    from nptyping.ndarray import NDArray
  File "/home/lazerson/anaconda3/envs/parastell_env/lib/python3.11/site-packages/nptyping/ndarray.py", line 40, in <module>
    from nptyping.shape import Shape
  File "/home/lazerson/anaconda3/envs/parastell_env/lib/python3.11/site-packages/nptyping/shape.py", line 29, in <module>
    from nptyping.shape_expression import (
  File "/home/lazerson/anaconda3/envs/parastell_env/lib/python3.11/site-packages/nptyping/shape_expression.py", line 36, in <module>
    from nptyping.typing_ import ShapeExpression, ShapeTuple
  File "/home/lazerson/anaconda3/envs/parastell_env/lib/python3.11/site-packages/nptyping/typing_.py", line 51, in <module>
    Bool8 = np.bool8
            ^^^^^^^^
  File "/home/lazerson/.local/lib/python3.11/site-packages/numpy-2.0.0-py3.11-linux-x86_64.egg/numpy/__init__.py", line 410, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'bool8'. Did you mean: 'bool'?
```

**Comment by lazersos** [comment]
This second issue seems to be related to the line in the environments.yml:
```yaml
 - numpy=1.26.4
```
as the `bool8` feature was depricated in 1.24, and I'm guessing removed by 1.26.4

**Comment by lazersos** [comment]
Update the issue seems to be with `pystell_uw` as it's build does not specify a version of numpy and so it's installing 2.0 which then meets the needs for `parastell` which of course it doesn't.

**Comment by connoramoreno** [comment]
Hi @lazersos, thanks for reaching out and apologies for the delay in response. Can you please confirm which version of NumPy is installed in your conda environment?

**Comment by connoramoreno** [comment]
@lazersos, it doesn't seem that the output you've provided includes information about your NumPy installation. To retrieve information about your NumPy installation via conda, you can run the following command in your terminal (with the proper conda environment activated):
```bash
conda activate parastell_env
conda list numpy
```

**Comment by lazersos** [comment]
@connoramoreno Sorry here you go:
```bash
conda list numpy
# packages in environment at /home/lazerson/anaconda3/envs/parastell_env:
#
# Name                    Version                   Build  Channel
numpy                     1.24.0          py311hbde0eaa_0    conda-forge
```

**Comment by lazersos** [comment]
@connoramoreno Yes, from what I can tell Conda has a `numpy 1.24.0` installed but pip has `numpy 2.0.0` installed as well. And when the code is envoked, the pip version is the one which is picked up first.

**Comment by lazersos** [comment]
A bit more digging and issue seems to be that `cadquery` which is needed by `cad_to_dagmc` is currently broken via pip and presumably conda (https://github.com/CadQuery/cadquery/issues/1714).

**Comment by connoramoreno** [comment]
I'm unfamiliar with `pip` installations of CadQuery but we have not experienced any issues with conda versions yet. CadQuery is a major dependency of ParaStell and is the software toolset we use to generate all of our CAD models, so any issues with CadQuery would likely make themselves quickly apparent.

As you mentioned, it seems that the conflict is occurring because Python is importing a version of NumPy that is outside your conda environment. Here are some potential solutions:

- Revert the `pip` installation of NumPy to an older version that is compatible with ParaStell.
- Uninstall the `pip` installation of NumPy and rely instead on installations via conda for your computational needs. You could create other conda environments or just use the ParaStell environment.
- Install ParaStell's Python dependencies via some method other than conda. This is what I would **least** recommend as our support for alternative dependency installation methods is limited.

**Comment by lazersos** [comment]
@connoramoreno Doing a `pip uninstall numpy` and then building the conda environment again seems to fix the issue. It's odd that the pip installations outside of conda would override conda. Anyway, thanks for the help.

**Comment by adam-urbanczyk** [comment]
> A bit more digging and issue seems to be that `cadquery` which is needed by `cad_to_dagmc` is currently broken via pip and presumably conda ([CadQuery/cadquery#1714](https://github.com/CadQuery/cadquery/issues/1714)).

AFAICT conda installation is not broken, but if you have a reproducible problem, please open an issue.
